### model
model_name_or_path: models/DeepSeek/DeepSeek-R1-Distill-Llama-8B
#resume_from_checkpoint: saves/DeepSeek/DeepSeek-R1-Distill-Llama-8B-cmnee/qlora/sft/66/checkpoint-4000
quantization_bit: 8
quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: CMNEE_LLMF_EE
template: deepseek3
cutoff_len: 2048
max_samples: 15000
overwrite_cache: true
preprocessing_num_workers: 24

### output
output_dir: saves/DeepSeek/DeepSeek-R1-Distill-Llama-8B-CMNEE-EE/qlora/2025_07_02
logging_steps: 4
save_steps: 600
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 8.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# enable_thinking: false

### eval
val_size: 0.2
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 600
