### model
model_name_or_path: models/Qwen/Qwen-2.5-7B-Instruct
quantization_bit: 4  # choices: [8 (bnb/hqq/eetq), 4 (bnb/hqq), 3 (hqq), 2 (hqq)]
quantization_method: bnb  # choices: [bnb, hqq, eetq]
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: q_proj,k_proj,v_proj,o_proj

### dataset
dataset: CMNEE_train
template: qwen
cutoff_len: 1024
max_samples: 15000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 16
enable_thinking: false

### output
output_dir: saves/Qwen/Qwen-2.5-7B-Instruct/CMNEE-new/qlora-sft
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 3.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500
